### ISSUE TITLE
How to use custom filter

### ISSUE THREAD

**Issue by sixpercentninja** [didierbrun/DBPathRecognizer#4]
Hey Didier (or anyone reading)

I'm trying to use this great library for a game I'm making, but it seems the recognizer is quite inaccurate for me.  

So I'm trying to put in some custom filters to better differentiate between the gestures, but I'm having a hard time understanding how to implement them.

Could you give me a sample code of how it would be used, to differentiate between the "B" and "P" as you mentioned in the readme?

Thank you!

**Comment by csr** [comment]
Agreed. Didier, some more documentation on custom filters would be great. For instance, how is "cost" determined? Thanks

**Comment by didierbrun** [comment]
Hello @sixpercentninja, @CeceXX,

The cost is a scalar value evaluating the distance between two paths. It is calculated by a derived Levenshtein algorithm [https://en.wikipedia.org/wiki/Levenshtein_distance](url). Lower is the cost value, closer is the similarity between the two paths.

However, since the algorithm do take into account only the sequential change directions in a row, it will not make the distinction between a D & a P, because in fact, the direction "sequence" is almost identical for these two shapes.

So the custom filter could be used to make a custom "code" to discriminate these particular cases. A dedicated PathInfos struct is passed as a argument to the custom filter, as well as the "cost" calculated by the algorithm (before filter). 

The custom filter should return a new cost value. Lower is the cost, more chance the candidate will be selected as the best candidate. Higher cost could be used to eliminate for sure the candidate. 

The PathInfos contains datas that help you to determine this new cost : 
deltaPoints:[PathPoint] - The raw points (x, y) and angle
boundingBox:Rect - The bounding box of the drawed path
directions:[Int] - The directions calculated (clock)

With these informations, you can calculate a new score which will replace the original.

For example, in a scenario of a "D" letter, I expect that the last point.y should never be <= 70% of the bounding box height. If it's the case, I eliminate the "D" candidate by returning a high score (remember lower is the cost, best is the candidate).

I hope these explanations will help you.

Best.

**Comment by csr** [comment]
Thank you very much Didier. That was really helpful.

**Comment by jm789** [comment]
Hey Didier,

Thanks for a great piece of code. I'm not sure whether you've noticed but with the release of Swift 3, there appears to be issues with some of the code. I'm still too inexperienced to fix this myself, so anyone's assistance will be highly appreciated.

Best.
